### ISSUE TITLE
d->namlen isn't universally available

### ISSUE THREAD

**Issue by mdorman** [jwiegley/pipes-files#1]
http://hydra.cryp.to/build/1055837/nixlog/2 has a build failure log.  The specific issue is:

Helper.c: In function ‘__hscore_d_namlen’:

    Helper.c:12:11:
         error: ‘struct dirent’ has no member named ‘d_namlen’
           return d->d_namlen;
                   ^

I don't have time to actually test this, but http://man7.org/linux/man-pages/man3/readdir.3.html would suggest that the right answer is something like:

    #ifdef _DIRENT_HAVE_D_NAMLEN
    return d->d_namlen;
    #else
    return strlen (d->d_name)
    #endif

**Comment by jwiegley** [comment]
Thanks, your recommended fix has been applied in 0.1.1.
